### ISSUE TITLE
Make file has a dist target but corresponding script is not there

### ISSUE THREAD

**Issue by miguelaferreira** [ninjasphere/driver-kodi#2]
Hi @elliots 

First off, thanks for the interest and the effort in supporting XBMC within the ninja environment.

I've saw your driver for the Ninja Block and now found this one for the Sphere. I'm an avid user of XBMC and I just got my sphere in the mail today, so here I am, ready to test and contribute to your project :)
(BTW I've already made a PR for renaming the binary that comes out of the build).

Now I was looking at the Makefile and saw that there is a target named dist that is calling a script that is not there. Do I need this goal to build a binary that I can put in my sphere? Or what comes out of the build target is enough?

One other thing: I'be built a binary with `make` and shipped it to the sphere, but then I get an error about the exec format. Any idea on how do I cross compile a binary on my Mac that will run on the sphere?

**Comment by wolfeidau** [comment]
Gday 

Checkout https://coderwall.com/p/pnfwxg/cross-compiling-golang to see how to get your mac ready for cross compile. You may need to reinstall go via homebrew with the cross compile flag.

Secondly to build for ARM and Linux run `make` as follows:

```
GOARCH=arm GOOS=linux make
```

Hope that helps, I am not sure how far along this driver is hopefully @elliots can chime in with an update.

**Comment by miguelaferreira** [comment]
Hi @wolfeidau 

Thanks for the help. I'm just running through http://dave.cheney.net/2012/09/08/an-introduction-to-cross-compilation-with-go
If that doesn't work I'll try your suggestion.

EDIT: no luck with the instruction I was following, I guess I do need that cross compile flag. Will keep you posted on progress.

**Comment by miguelaferreira** [comment]
Got cross compiling working and driver is running on my sphere :) Thanks guys!

Answering my initial question: no, there is no need for the dist target in Makefile.

I now have more questions, but will open a new thread for that.
